export const HOST_MEETING_START = 'HOST_MEETING_START';
export const HOST_MEETING_SUCCESS = 'HOST_MEETING_SUCCESS';
export const HOST_MEETING_FAIL = 'HOST_MEETING_FAIL';

export const SCHEDULE_MEETING_START = 'SCHEDULE_MEETING_START';
export const SCHEDULE_MEETING_SUCCESS = 'HOST_MEETING_SUCCESS';
export const SCHEDULE_MEETING_FAIL = 'SCHEDULE_MEETING_FAIL';

export const END_MEETING_START = 'END_MEETING_START';
export const END_MEETING_SUCCESS = 'END_MEETING_SUCCESS';
export const END_MEETING_FAIL = 'END_MEETING_FAIL';

export const JOIN_MEETING_START = 'JOIN_MEETING_START';
export const JOIN_MEETING_SUCCESS = 'JOIN_MEETING_SUCCESS';
export const JOIN_MEETING_FAIL = 'JOIN_MEETING_FAIL';


export const CLEAR_MEETING_ERRORS = 'CLEAR_MEETING_ERRORS';
